### ISSUE TITLE
[featureRequest] Optionally do not group links to "Neo Diggler" submenu

### ISSUE THREAD

**Issue by vvch** [fnxweb/neo-diggler#10]
Currently all Diggler links are grouped to "Neo Diggler" submenu of right-click menu. It could save one click if they would be placed (optionally) directly to the right-click menu, without submenu

**Comment by fnxweb** [comment]
Firefox doesn't let you add extension menu items to its own menus any more:  all extension additions are automatically grouped under the extension's name (this is true of main-page context menu extensions as well).

Not sure what you mean by an extra click, though?  You still only click once to get the context menu, then drag right to the Neo Diggler submenu, or are we not talking about the same thing?

**Comment by vvch** [comment]
No, we are talking about the same thing. Your extension is about convenience and saving some manual actions, so I decided this improvement can help save some move movement :)  It's a pity that Firefox doesn't allow that but seems like nothing can be done here.

**Comment by fnxweb** [comment]
Yeah, I had a similar issue with my other extension which used to directly amend the core content menu. No longer possible. 🙁
