### ISSUE TITLE
Subdomain -> domain navigation

### ISSUE THREAD

**Issue by bdcomp** [fnxweb/neo-diggler#2]
It would be great to have an additional option in the navigation menu for:
```
current url: sub.domain.com
menu option: domain.com
```

**Comment by fnxweb** [comment]
You should be able to do that by adding a custom tool in the preferences.

**Comment by bdcomp** [comment]
Probably most of the users not familiar with regex, while it may be useful for many of them.
I think it should be built-in.

**Comment by fnxweb** [comment]
I'm disinclined to add more built-in rules where the prefs. can accommodate them.  I'm happy to help out with regex queries.

In this instance, you should be able to achieve your goal with:

**Tool Action**:  `Prime Domain`
**Regex**:  `^([^:]+://)[^./]+\.([^/]+/).*$`
**Action**:  `$1$2`

I also recommend ticking _“Use the action as the menu label”_ for this one.

That said, my first attempt found a bug on the prefs. dialogue:  you can't currently have a **|** in the regex, I'll fix that shortly.

**Comment by fnxweb** [comment]
Fix for pipes in regex: 6b2cd6ef156582dc8452d7a7a4591f10b0e10d3e  (previously f333cf76edfd5a5a5517a22caa0fa8401da6617c)
