### ISSUE TITLE
Edit current URL parameters (GET arguments)

### ISSUE THREAD

**Issue by MurzNN** [fnxweb/neo-diggler#4]
Will be good to have ability for edit current url parameters (GET arguments) in your extension (display each GET argument as decoded text in separate input box), as alternative to https://addons.mozilla.org/ru/firefox/addon/yaediturl/ extension that stops working on Firefox 57+, or maybe as separate extension.

**Comment by fnxweb** [comment]
That's quite wildly out of scope, but I'll have a think...

**Comment by fnxweb** [comment]
OK, the above commit allows you to supply **javascript:** actions as a custom tool.  I'll put together a 2.1.0 with it in after I've done entering this.

Bear in mind that I've done this as a bit of an academic exercise, really to prove it's possible, so it's not gonna mimic what that other extension does (but, as I said, it's out of scope for this one, really).  But the whole point of [Neo] Diggler is _user_ customisation, so here you go.

The following Javascript is my baseline;  sandboxing issues mean the “apply” function needs to be an inline-string (the source is there and commented out).  I minified the (uncommented) function body, and quote-escaped it for the **apply** variable.  I then minified the rest of the JS, and that's what you can use as a custom tool.  If you wish to extend it (it doesn't allow deletion or addition of args. as it is) then you can repeat the above process.  Pasting the full-fat JS into the console (**F12**) works as a test.

For ref. I used https://jscompress.com/ for minifying, with the _ECMAScript 2.0_ box ticked.

### Source
```javascript
url = window.location.href.split("?")
args = url[1].split("&")

div = document.createElement("div")
div.id = "__div_"
document.getElementsByTagName("body")[0].appendChild(div)

div.style = "position:fixed;width:75%;height:75%;border:2px solid;border-radius:8px;top:12.5%;left:12.5%;z-index:1000000;background:#fff;padding:1em"

inner = `<p><span>Host</span><br><input style="width:95%" id="__srv_" type="text" value="${url[0]}">`
for (let idx in Object.keys(args))
{
    let pair = args[idx].split("=")
    inner += `<p><span id="__key_${idx}_">${pair[0]}</span><br><input style="width:95%" id="__val_${idx}_" type="text" value="${pair[1]}">`
}

apply = "let div=document.getElementById(\'__div_\'),targ=document.getElementById(\'__srv_\').value+\'?\',idx=-1;for(;;){let a=document.getElementById(`__key_${++idx}_`);if(!a)break;0<idx&&(targ+=\'&\'),targ+=a.innerText+\'=\'+document.getElementById(`__val_${idx}_`).value}window.location.href=targ"
inner += `<p><input type="button" value="Go" onclick="${apply}">`

// function __apply__()
// {
//     let div = document.getElementById("__div_")
//     let targ = document.getElementById("__srv_").value + "?"
//     let idx = -1
//     while (1)
//     {
//         let key = document.getElementById(`__key_${++idx}_`)
//         if (!key)
//             break
//         if (idx > 0)
//             targ += "&"
//         targ += key.innerText + "=" + document.getElementById(`__val_${idx}_`).value
//     }
//     alert(targ)
//     //window.location.href = targ
// }

div.innerHTML = inner
```

### Minified
```javascript
javascript:for(let a in url=window.location.href.split("?"),args=url[1].split("&"),div=document.createElement("div"),div.id="__div_",document.getElementsByTagName("body")[0].appendChild(div),div.style="position:fixed;width:75%;height:75%;border:2px solid;border-radius:8px;top:12.5%;left:12.5%;z-index:1000000;background:#fff;padding:1em",inner=`<p><span>Host</span><br><input style="width:95%" id="__srv_" type="text" value="${url[0]}">`,Object.keys(args)){let b=args[a].split("=");inner+=`<p><span id="__key_${a}_">${b[0]}</span><br><input style="width:95%" id="__val_${a}_" type="text" value="${b[1]}">`}apply="let div=document.getElementById('__div_'),targ=document.getElementById('__srv_').value+'?',idx=-1;for(;;){let a=document.getElementById(`__key_${++idx}_`);if(!a)break;0<idx&&(targ+='&'),targ+=a.innerText+'='+document.getElementById(`__val_${idx}_`).value}window.location.href=targ",inner+=`<p><input type="button" value="Go" onclick="${apply}">`,div.innerHTML=inner
```

### Instructions
- In the Neo Diggler prefs. page, create a new custom tool
  - **Name** — whatever you want
  - **Action will be matched** — _e.g._, `^(.+)\?(.*)$`
  - **Action** — Paste here the minified line of code above (starting with _javascript:..._)
- Apply the _Tool Action_ popup, then apply the prefs., then you should be good to go.
- You may need to reload any already-open pages to test on, jut to be sure.

It worked for me, with limited testing on a google search.

**Comment by MurzNN** [comment]
Thanks, work like a charm! Will be good to create public database with useful code snippets like this.
I create a feature request about this: https://github.com/fnxweb/neo-diggler/issues/5

**Comment by fnxweb** [comment]
Good;  soz I ran out of time to think about add and delete for that list.
