### ISSUE TITLE
Repository with list of useful code snippets in Neo Digger

### ISSUE THREAD

**Issue by MurzNN** [fnxweb/neo-diggler#5]
Neo Digger allow to create many useful short scripts to automate many things, eg like this: https://github.com/fnxweb/neo-diggler/issues/4#issuecomment-381318096

Will be good to create a Neo Digger repository with useful custom scripts. Maybe we can use a GitHub Wiki for this in current project?

**Comment by fnxweb** [comment]
Sounds like an idea, I'll look at how the GitHub wiki works and is configured, esp. for”open” edits.

**Comment by fnxweb** [comment]
OK, check out https://github.com/fnxweb/neo-diggler/wiki .
